import { kitql } from '@kitql/eslint-config'

/** @type { import('eslint').Linter.Config[]} */
export default [
	// Generated by paraglide, not ours to lint.
	{ ignores: ['src/lib/paraglide/**', 'src/lib/ROUTES.ts'] },
	...kitql(),
]
